### PR TITLE
Recipe and diag_scripts for common basis function

### PR DESCRIPTION
**Pull request by YanchunHe**
* add `recipe_cbf.yml`
* add diagnostic script `cbfs.py`, and a test script `test_cbfs.py`
* to do: need better integrated with ESMValTool `config` dictionary to digest data and sort created figures.

### CODE REVIEW

**Comment by tommibergman** [comment]
It still doesn't have download for the observational data, but since workshop is tomorrow I approved the pull request. We can correct things later.

**Comment by YanchunHe** [comment]
This is Tier 3 observation, so it has to be downloaded manually.

**Comment by tommibergman** [comment]
But I think it should include information where it can be retrieved. Or did  I miss it?

**Comment by YanchunHe** [comment]
yes, specified in  the `cmorizers/cmorize_era20c.sh`.
Of course, I admit that this is not well documented.

**Pull request merged**
